replicaCount: 1
image:
  debug: true
controller:
  replicaCount: 1
tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Equal"
    value: ""
    effect: "NoSchedule"
kraft:
  enabled: true
zookeeper:
  enabled: false
  replicaCount: 1
listeners:
  client:
    protocol: PLAINTEXT
extraConfig: |
  offsets.topic.replication.factor=1
  transaction.state.log.replication.factor=1