apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "react-chart.fullname" . }}
  labels:
    {{- include "react-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "react-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "react-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
