apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rest-multiple-db-chart.fullname" . }}
  labels:
    {{- include "rest-multiple-db-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "rest-multiple-db-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rest-multiple-db-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /api/access/status
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 60
          livenessProbe:
            httpGet:
              path: /api/access/status
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 60
