apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "istio-chart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "istio-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "istio-chart.chart" . }}
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
    - port:
        number: {{ .Values.service.port }}
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "istio-chart.fullname" . }}
spec:
  hosts:
  - "*"

  gateways:
    - {{ include "istio-chart.fullname" . }}
  http:
  {{- range $app := .Values.apps }}
  - match:
      - uri:
          prefix: "{{ $app.name }}"
    route:
      - destination:
          port:
            number: {{ $app.port }}
          host: "{{ $app.deployment }}"
  {{- end }}
  - route:
      - destination:
          port:
            number: 3000
          host: react-service
