apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  labels:
    app: mysql
    app.kubernetes.io/name: mysql
data:
  primary.cnf: |
    [mysqld]
    default_authentication_plugin = mysql_native_password
    log-bin

  replica.cnf: |
    [mysqld]
    default_authentication_plugin = mysql_native_password
    super-read-only
    
