releases:

  - name: mysql-chart-release
    chart: ./charts/mysql-chart
    namespace: default
    installed: true

  - name: react-chart-release
    chart: ./charts/react-chart
    namespace: default
    installed: true

  - name: rest-chart-release
    chart: ./charts/rest-chart
    namespace: default
    installed: true

  - name: websocket-chart-release
    chart: ./charts/websocket-chart
    namespace: default
    installed: true

  - name: istio-chart-release
    chart: ./charts/istio-chart
    namespace: default
    installed: true
