environments:
  default:
  single:
    values:
      - restDB: ./charts/rest-chart
  multiple:
    values:
      - restDB: ./charts/rest-multiple-db-chart
---
releases:
  - name: istio-chart-release
    chart: ./charts/istio-chart
    namespace: myapp
    installed: true

  - name: react-chart-release
    chart: ./charts/react-chart
    namespace: myapp
    installed: true


  - name: rest-db-chart-release
    chart: {{ .Values.restDB }}
    namespace: myapp
    installed: true


  - name: websocket-chart-release
    chart: ./charts/websocket-chart
    namespace: myapp
    installed: true



